module SpriteID

  PLAYER1, PLAYER2, MENU_SHEET, THRUST, SPACE_BACKGROUND, BACKGROUND, STAR,
  NORMAL_JIZZ, JIZZ_EFFECT, SMOKE_EFFECT, HEALTH_BONUS, AMMO_BONUS, FIRE,
  FIRE_POWER_UP, SUPER_SPEED_POWER_UP = *0..14

end